name: Deploy to Azure VM

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key for Azure VM
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}

      - name: SSH into Azure VM and Deploy Docker
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@<your-vm-public-ip> << 'EOF'
            # Pull the latest image from DockerHub
            docker pull yourdockerhubusername/presentify:latest

            # Stop any running container (optional)
            docker stop presentify || true
            docker rm presentify || true

            # Run the new container
            docker run -d -p 3000:3000 --name presentify yourdockerhubusername/presentify:latest
          EOF
